### ISSUE TITLE
fcenter.ru кажеться trim() не срабатывает

### ISSUE THREAD

**Issue by akmorp** [sleeping-owl/apist#4]
class FCenterAPI extends Apist
{

    public function getBaseUrl()
    {
        return 'http://fcenter.ru/product/goods/';
    }

    public function product($SKU)
    {
        return $this->get($SKU,[
            'properties' => Apist::filter('table.striped.techpars > tr')->each([
                'name' => Apist::filter('th')->text()->rtrim()->ltrim(),
                'value' => Apist::filter('td')->text()->trim()
            ])
        ]);
    }

}

$fcenterapi = new FCenterAPI();
$result = $fcenterapi->product('126852');

![fcenter](https://cloud.githubusercontent.com/assets/6882182/6128407/929ddf3a-b146-11e4-91b9-3d3d1f7e5b57.png)

**Comment by sleeping-owl** [comment]
Поправил, теперь должно работать как положено. Обнови пакет до последней версии.

**Comment by akmorp** [comment]
class FCenterAPI extends Apist
{

    public function getBaseUrl()
    {
        return 'http://fcenter.ru/product/goods/';
    }

    public function product($SKU)
    {
        return $this->get($SKU, array(
            'properties' => Apist::filter('table.striped.techpars > tr')->each(array(
                'name' => Apist::filter('th')->text()->trim(),
                'value' => Apist::filter('td')->text()->trim()
            )),
            'images' => Apist::filter('div.pic-preview a')->each(Apist::current()->attr('href'))
        ));
    }

}

$fcenterapi = new FCenterAPI();
$result = $fcenterapi->product('127617');

Подскажите пожалуйста.
Не могу сообразить как мне получить вот такую структуру ответа:

Array
(
    [properties] => Array
        (
            [Особенности] => Array
                (
                    [0] => Встроенные динамик и микрофон
                    [1] => Датчик движения
                    [2] => Ночной режим (без подсветки)
                    [3] => G-сенсор
                )

            [Питание] => Array
                (
                    [0] => Встроенный аккумулятор Li-Pol 3.7 В
                    [1] => От гнезда автомобильного прикуривателя
                )

            [Вес] => Array
                (
                    [0] => 61 г
                )

        )

    [images] => Array
        (
            [Вид cпереди 1] => http://img.fcenter.ru/goodsimages/127000/127600/127617/424635_L.jpg
            [Вид сзади] => http://img.fcenter.ru/goodsimages/127000/127600/127617/424756_L.jpg
            [Разъемы] => http://img.fcenter.ru/goodsimages/127000/127600/127617/424757_L.jpg
            [Комплектация] => http://img.fcenter.ru/goodsimages/127000/127600/127617/424758_L.jpg
            [Коробка] => http://img.fcenter.ru/goodsimages/127000/127600/127617/424759_L.jpg
        )

)


Учитывая что, например в [Особености] значение еще разделено внутри тегом <br> (http://fcenter.ru/product/goods/127617), а в [Вес] его нет, и с [images] непонятно.
Спасибо за оперативное исправление trim().

**Comment by sleeping-owl** [comment]
К сожалению мой пакет не может строить такие структуры, а конкретно использовать вычисляемые значения в качестве ключей в массиве. Твою задачу можно решить следующим образом (массив будет несколько иного вида, но думаю использовать можно):
```php
public function product($SKU)
{
	return $this->get($SKU, [
		'properties' => Apist::filter('table.striped.techpars > tr')->each([
			'name' => Apist::filter('th')->text()->trim(),
			'value' => Apist::filter('td')->html()->str_replace(["\n", "\t"], '')->call(function ($item)
			{
				return explode('<br>', $item);
			})->trim()
		]),
		'images' => Apist::filter('div.pic-preview a')->each([
			'href' => Apist::current()->attr('href'),
			'title' => Apist::filter('img')->attr('alt')
		])
	]);
}
```

При большой необходимости можно просто добавить преобразование массива в нужный вид.

**Comment by akmorp** [comment]
Спасибо, подойдет, дальше преобразую в нужный вид.
