### ISSUE TITLE
Редирект

### ISSUE THREAD

**Issue by KoBa4** [sleeping-owl/apist#9]
Есть такой код:
```php
include 'vendor/autoload.php';
use SleepingOwl\Apist\Apist;

class LostFilmApi extends Apist
{
    public function getBaseUrl()
    {
        return 'http://www.lostfilm.tv/';
    }

    public function getTorrents($seriesId, $season, $episode)
    {
        return $this->get('/nrdr2.php', Apist::filter('div div:nth-child(6)')->each(
            [
                'type' => Apist::current()
                    ->filter('td[style="width:55px;"] img')
                    ->attr('src')->ltrim('img/search')->ltrim("_")->rtrim('.png'),
                'link' => Apist::current()->filter('div nobr a')->attr('href')
            ]
        ),
            [
                'query' => [
                    'c' => $seriesId,
                    's' => $season,
                    'e' => $episode
                ],
                'headers' => [
                    'Cookie' => 'uid=xxxxxx; pass=xxxxxxxxxxxxxxxxxx; usess=xxxxxxxxxxxxxxxxxxxx'
                ]
            ]
        );
    }

}
```
Ссылка для отправки GET запроса в итоге выглядит к примеру так `http://www.lostfilm.tv/nrdr2.php?c=176&s=4&e=99`, но при переходе по ней происходит редирект на такую страницу `http://retre.org/?c=176&s=4&e=99&u=3594923&h=53cfecd4ef2bdbd276457cac35a86b97` и в итоге код возвращает пустой массив.
И у меня возник такой вопрос. Реализована ли у вас возможность следовать за редиректом, как это сделано в cURL? Или может я где-то ошибся?
Буду признателен за помощь.

**Comment by erickskrauch** [comment]
@KoBa4, эта библиотека использует Guzzle для своей работы, так что эти настройки нужно смотреть внутри. Оригинальная библиотека использует Guzzle 5 и довольно давно не обновлялась, но вроде как тут вполне реально подлезть к конфигурации Guzzle.

Или же ты можешь использовать [наш форк](https://github.com/elyby/apist) с поддержкой Guzzle 6 и передачей [сконфигурированного](http://docs.guzzlephp.org/en/latest/quickstart.html#redirects) клиента в конструкторе. API немного отличается, но если будет нужно, то могу помочь освоиться.

**Comment by KoBa4** [comment]
@erickskrauch, Я попробовал ваш форк, подправил код и если сможешь помочь, то вот [Gist](https://gist.github.com/KoBa4/98225f593b5761dcdac88e2281137796)
